setwd("C:/Users/caitlyn jones/OneDrive/classes/math/statistical modelling/Coursework")
oscars <- read.csv("oscars.csv", header = TRUE)
oscars <- oscars[oscars$Ch != 0, ]
oscars$Ch <- ifelse(oscars$Ch == 1, 1, 0)
full_model <- glm(Ch ~ Nom + Pic + Dir + Aml + Afl + Ams + Afs + Scr + Cin + Art + Cos + Sco + Son + Edi + Sou + For + Anf + Eff + Mak + Dan + AD + Gdr + Gmc + Gd + Gm1 + Gm2 + Gf1 + Gf2 + PGA + DGA + Action + Adventure + Animation + Biography + Comedy + Crime + Docu + Drama + Family + Fantasy + Film.noir + History + Horror + Music + Musical + Mystery + Romance + SciFi + Sport + Thriller + War + Western + Length + Days + G + PG + PG13 + R + U + Ebert + NYFCC + LAFCA + NSFC + NBR + WR, data = oscars, family = binomial)
summary(full_model)
exp(coef(full_model)["Dir"])
confint(full_model, "Dir")
library(MASS)
best_model <- step(full_model, direction = "both")
summary(best_model)
library(pROC)
predicted_probs <- predict(best_model, type ="response")
roc_curve <- roc(oscars$Ch, predicted_probs)
plot(roc_curve, main = "ROC Curve for Best Picture Model")
auc_value <- auc(roc_curve)
print(auc_value)
opt_thresh <- coords(roc_curve, "best", ret = "threshold")
print(opt_thresh)
str(predicted_probs)
str(oscars$Ch)
predicted_probs <- as.numeric(predicted_probs)
pred_class <- ifelse(predicted_probs >= opt_thresh, 1, 0)
opt_thresh <- as.numeric(opt_thresh)
pred_class <- ifelse(predicted_probs >= opt_thresh, 1, 0)
con_mat <- table(Predicted = pred_class, Actual = oscars$Ch)
sensitivity <- con_mat[2,2] / (con_mat[2,2] + con_mat[1,2])
print(sensitivity)
oscars <- read.csv("oscars.csv", header = TRUE)
curr_noms <- oscars[oscars$Ch == 0,]
curr_noms$Predicted_Prob <- predict(best_model, newdata = curr_noms, type = "response")
curr_noms$Normalized_Prob <- curr_noms$Predicted_Prob / sum(curr_noms$Predicted_Prob)
results <- curr_noms[, c("Name", "Normalized_Prob")]
print(results)

